# Generated by Django 3.1.6 on 2021-04-27 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210427_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
