# Generated by Django 3.1.6 on 2021-04-30 08:34

from django.db import migrations

def load_categories(apps, schema_editor):
    Category = apps.get_model("auctions", "Category")

    category_art = Category(id=8,title="Art")
    category_art.save()

    category_instuments = Category(id=9,title="Instruments")
    category_instuments.save()

    category_jewerly = Category(id=10,title="Jewerly & Watches")
    category_jewerly.save()

    category_health = Category(id=11,title="Health & Beauty")
    category_health.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_closing_date'),
    ]

    operations = [
        migrations.RunPython(load_categories)
    ]
